name: libsass
version: 0.0.1
author: Dariel Dato-on <oddrationale@gmail.com>
description: A Dart VM Native Extension for libsass
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.12.2 <1.0.0'
dev_dependencies:
  unittest: any
executables:
  sassd: sassd
